Un array (Matriz): tiene como caracteristica un conjunto de datos del mismo tipo, contrario a las listas.
Los arrays pueden manejar directamente operaciones aritmeticas. Las listas no.

Matrices sin Numpy

In [1]:
import array as ar
matriz = ar.array('i',[1,2,3,4,5]) # la 'i' es de INT y 'd' se usaria para decimales.
print(matriz)

array('i', [1, 2, 3, 4, 5])


In [1]:
import array as ar
matriz = ar.array('i',[1,2,3,4,5]) # la 'i' es de INT y 'd' se usaria para decimales.
for ar in matriz:
    print(ar)

1
2
3
4
5


Matrices con Numpy

In [2]:
import numpy as np
matriz = np.array([1,2,3,4,5])
print(matriz)

[1 2 3 4 5]


In [3]:
import numpy as np

lista = [1,3,5]
matriz = np.array([2,4,6])
print(lista) # la lista es una coleccion de elementos.
print(matriz) # crea elementos independiente, y cada uno ocupa un lugar en la memoria.

[1, 3, 5]
[2 4 6]


In [5]:
import numpy as np

lista = [1,3,5]
matriz = np.array([2,4,6])
lista.append(7)
#matriz.append(8) esto no funciona.
matriz = matriz + np.array([8]) # esto lo que hace es sumarse a la matriz, no continua una secuencia de numeros.
print(lista) # la lista es una coleccion de elementos.
print(matriz) # crea elementos independiente, y cada uno ocupa un lugar en la memoria.

[1, 3, 5, 7]
[10 12 14]


In [6]:
import numpy as np

a = [1,2,3] # LISTA
b = [4,5,6] # LISTA

print(a+b) # aca no se suman, se concatenan

[1, 2, 3, 4, 5, 6]


In [10]:
import numpy as np

a = np.array([1,2,3]) # ARRAY
b = np.array([4,5,6]) # ARRAY

print(a+b) # aca sí suman

[5 7 9]


Matrices con Listas

In [12]:
import numpy as np

m2d = np.array([[1,2,3],[4,5,6]]) # primer corchete primera dimension, segundo la segunda.
print(m2d)



[[1 2 3]
 [4 5 6]]


In [14]:
import numpy as np
lista = [1,2,3,4,5]
matriz = np.array(lista)
print (matriz)

[1 2 3 4 5]


In [15]:
import numpy as np
lista = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(lista)
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
m = np.arange(15).reshape(3,5) #con esto generamos matrices de, (arange) ,15 alementos divididos, (resshape), en 3 filas y 5 columnas. 
print(m) #dato clave: si no alcanzas las filas/columnas para la cantidad de numeros en arange va a dar error.


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [19]:
m = np.arange(15).reshape(3,5)
print(m.shape) # para saber como es la matriz
print(m.ndim) # numero de dimensiones o ejes.
print(m.size) # tamaño o cantida de elementos.
print(m) 

(3, 5)
2
15
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [21]:
m = np.zeros((3,4)) #matriz de ceros
print(m.shape) # para saber como es la matriz
print(m.ndim) # numero de dimensiones o ejes.
print(m.size) # tamaño o cantida de elementos.
print(m)

(3, 4)
2
12
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
m = np.arange(10) # matriz de una sola dimension
print(m.shape) # para saber como es la matriz
print(m.ndim) # numero de dimensiones o ejes.
print(m.size) # tamaño o cantida de elementos.
print(m)

(10,)
1
10
[0 1 2 3 4 5 6 7 8 9]


In [23]:
m = np.linspace(99,88,25) # generar matricer de manera aleatoria desde 99 a 88 con 25 elementos.
print(m.shape) # para saber como es la matriz
print(m.ndim) # numero de dimensiones o ejes.
print(m.size) # tamaño o cantida de elementos.
print(m)

(25,)
1
25
[99.         98.54166667 98.08333333 97.625      97.16666667 96.70833333
 96.25       95.79166667 95.33333333 94.875      94.41666667 93.95833333
 93.5        93.04166667 92.58333333 92.125      91.66666667 91.20833333
 90.75       90.29166667 89.83333333 89.375      88.91666667 88.45833333
 88.        ]


In [29]:
m = np.arange(24).reshape(2,3,4) # aca me esta diciendo que va a armar dos matrices de 3 filas y 4 columnas. 
print(m.shape) # para saber como es la matriz
print(m.ndim) # numero de dimensiones o ejes.
print(m.size) # tamaño o cantida de elementos.
print(m)

(2, 3, 4)
3
24
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [30]:
m = np.arange(27).reshape(3,3,3) # aca me esta diciendo que va a armar 3 matrices de 3 filas y 3 columnas. 
print(m.shape) # para saber como es la matriz
print(m.ndim) # numero de dimensiones o ejes.
print(m.size) # tamaño o cantida de elementos.
print(m)

(3, 3, 3)
3
27
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


Operaciones basicas con matrices: